# GNM/ViNT/Nomad Navigation Configuration for BRL Robot
# These values serve as defaults and can be overridden by command-line arguments.

# --- Model Configuration ---
# model: "nomad" (default) or other supported models in config/models.yaml
model: "gnm" 

# device: "cuda" (default) or "cpu"
device: "cuda"

# --- Topomap Configuration ---
# dir: "topomap" (default) - Name of the folder in deployment/topomaps/images/{topomap}
dir: "simu_0119_1"

# goal_node: -1 (default) - Index of the goal node. -1 means the last node.
goal_node: -1

# --- Navigation Parameters ---
# waypoint: 2 (default) - Index of the predicted waypoint to track (0-based).
# Increase this if increasing frame_rate/control frequency to avoid oscillation.
# GNM: [0,4]
waypoint: 4

# close_threshold: 3 (default) - Distance threshold to determine if a node is reached/close.
close_threshold: 3

# radius: 4 (default) - Temporal search radius for localization (number of nodes).
radius: 4

# num_samples: 8 (default) - Number of actions sampled from the exploration model.
num_samples: 8

# linear and angular speed limits for the robot
max_v: 0.5 #0.4 # m/s
max_w: 1.5 #0.8 # rad/s
# observation rate fo the robot
frame_rate: 10 # Hz
graph_rate: 0.3333 # Hz 
control_frequency: 20 # (default:9)Hz 

# PD GAINS
kp_v: 1.0
kp_w: 0.2

# Model config
trajs_scale_flag: false

# topic names (modify for different robots/nodes)
vel_teleop_topic: /cmd_vel_mux/input/teleop 
vel_navi_topic: /cmd_vel
vel_recovery_topic: /cmd_vel_mux/input/recovery
use_stamped_vel: true # Set to true if your robot requires geometry_msgs/TwistStamped
