# linear and angular speed limits for the robot
max_v: 0.26 #0.4 # m/s
max_w: 0.3 #0.8 # rad/s
# observation rate fo the robot
frame_rate: 10 # Hz
graph_rate: 0.3333 # Hz 
control_frequency: 30 # (default:9)Hz 

# PD GAINS
kp_v: 1.0
kp_w: 0.2


# topic names (modify for different robots/nodes)
vel_teleop_topic: /cmd_vel_mux/input/teleop 
vel_navi_topic: /cmd_vel
vel_recovery_topic: /cmd_vel_mux/input/recovery
use_stamped_vel: true # Set to true if your robot requires geometry_msgs/TwistStamped